version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build
          command: dotnet build --configuration Release
          working_directory: THT.AWS.Abstractions
      - run:
          name: Test
          command: dotnet test
          working_directory: THT.AWS.Abstractions.Tests
  release:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Pack
          command: dotnet build --configuration Release
          working_directory: THT.AWS.Abstractions
      - run: 
          name: Publish
          command: dotnet nuget push bin/Release/*.nupkg -k $NUGET_KEY -s https://www.nuget.org/
          working_directory: THT.AWS.Abstractions

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - hold:
        type: approval
        filters:
          branches:
            only: master
        requires:
          - build
    - release:
        requires: 
          - hold
