version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build
          command: dotnet build --configuration Release
          working_directory: THT.AWS.Abstractions
  release:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Nuget Publish
          command: echo do publish...

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - release:
        filters:
          branches:
            only: release
        requires:
          - build
